### PR TITLE
ANY.RUN: New App - new connector

### PR DESCRIPTION
**Pull request by anyrun-integrations**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [x] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [x] If this is a new connector or you are adding new actions
    - [x] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [x] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by edro15** [comment]
@anyrun-integrations - This submission is great! Is this connector going to fully replace community developed https://github.com/splunk-soar-connectors/anyrun ?

**Comment by t0x01** [comment]
@edro15 - Preferably yes, with time. We plan to fully support this connector in a long run and improve it, based on our clients feedback. I still consider it an early version and i'm pretty sure that there will be many changes to it, since our API will evolve and improve as well.

**Comment by anyrun-integrations** [comment]
@edro15 - Preferably yes, with time. We plan to fully support this connector in a long run and improve it, based on our clients feedback. I still consider it an early version and i'm pretty sure that there will be many changes to it, since our API will evolve and improve as well.

**Comment by ishans-crest** [comment]
Hi @anyrun-integrations 
Our security system has detected a security vulnerability in the 3.9.3 version of the 'aiohttp' library. These vulnerability issues are fixed in the version 3.9.4 
So, we would recommend that we update the library version 3.9.4
Please provide your feedback regarding the same.

**Comment by anyrun-integrations** [comment]
Hey @ishans-crest 
I've replaced 3.9.3 with 3.9.4 in the last commit. Please have a look.

**Comment by ishans-crest** [comment]
Hi @anyrun-integrations.

There seems to be a typo in the licensing of your pip package - [here](https://pypi.org/project/anyrun/#:~:text=License%3A%20pache%20Software%20License%202.0)
It is one of the reasons why the static test is failing.

**Comment by anyrun-integrations** [comment]
Hi @ishans-crest 
**anyrun** pip package isn't ours. In this app we use a different package that wasn't published yet - **anyrun-py**. I can remove it from requirements.txt for now, if it's an option.

**Comment by ishans-crest** [comment]
Hi @anyrun-integrations 
Yes. Please remove it from the requirements.txt if the code doesn't use it.

**Review by mishalp-crest — APPROVED** [review]

**Comment by ishans-crest** [comment]
Hi @anyrun-integrations 
We have made the necessary changes from our end.
Could you please test the latest code from your end?
Thank you.

**Comment by ishans-crest** [comment]
Absolutely. Do upgrade the Library. Please re-test the app after doing so. 

Thanks.

**Comment by anyrun-integrations** [comment]
Hello.
We have some changes planned for our API, that will require some parts of the app to be adjusted. The changes are expected to be implemented within next 2 weeks. Can we delay the app release until then?

**Comment by anyrun-integrations** [comment]
Hey @ishans-crest 
We have finished testing, everything seems to be working as expected. Apologies for keeping you waiting, please take a look.

**Review by mishalp-crest — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
